### ISSUE TITLE
Cython Value Error

### ISSUE THREAD

**Issue by StCross** [tridungduong16/multiobj-scm-cf#1]
Hello I am using your work to generat CFs for my Thesis. However, when I run `run_credit.py` I got error like this: `ValueError: Buffer has wrong number of dimensions (expected 2, got 1)`.
The full ErrorTrace:
```
2022-05-09 11:34:47,270 genetic      DEBUG    Store result
2022-05-09 11:34:48,070 genetic      DEBUG    Number of samples 2
2022-05-09 11:34:48,070 genetic      DEBUG    Sample 0
2022-05-09 11:34:48,098 genetic      DEBUG    Define algorithm
2022-05-09 11:34:48,101 genetic      DEBUG    Run optimization progress
Traceback (most recent call last):
  File "src\run_credit.py", line 208, in <module>
    verbose=True)
  File "D:\Anaconda3\envs\py37_tf1\lib\site-packages\pymoo\optimize.py", line 85, in minimize
    res = algorithm.solve()
  File "D:\Anaconda3\envs\py37_tf1\lib\site-packages\pymoo\model\algorithm.py", line 226, in solve
    self._solve(self.problem)
  File "D:\Anaconda3\envs\py37_tf1\lib\site-packages\pymoo\model\algorithm.py", line 321, in _solve
    self.next()
  File "D:\Anaconda3\envs\py37_tf1\lib\site-packages\pymoo\model\algorithm.py", line 243, in next
    self.initialize()
  File "D:\Anaconda3\envs\py37_tf1\lib\site-packages\pymoo\model\algorithm.py", line 215, in initialize
    self._initialize()
  File "D:\Anaconda3\envs\py37_tf1\lib\site-packages\pymoo\algorithms\genetic_algorithm.py", line 86, in _initialize
    n_min_infeas_survive=self.min_infeas_pop_size)
  File "D:\Anaconda3\envs\py37_tf1\lib\site-packages\pymoo\model\survival.py", line 120, in do
o\util\nds\non_dominated_sorting.py", line 26, in do
    fronts = func(F, **kwargs)
  File "pymoo\cython\non_dominated_sorting.pyx", line 25, in pymoo.cython.non_dominated_sorting.fast_non_dominated_sort
ValueError: Buffer has wrong number of dimensions (expected 2, got 1)
```
My environments:
- cpu : core i7
- gpu : gtx 950m
- python : 3.7.5
- packages : same as those in requirements.txt

I really appriciate it if you can help me, thanks

**Comment by StCross** [comment]
solved
